//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduates
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GraduatesEntities : DbContext
    {
        public GraduatesEntities()
            : base("name=GraduatesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Name_of_the_educational_institution> Name_of_the_educational_institution { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Storage_objects> Storage_objects { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Teacher> Student_Teacher { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Type_of_institution> Type_of_institution { get; set; }
        public virtual DbSet<Type_storage_object> Type_storage_object { get; set; }
    }
}
